name: manage-azure-policy-3ab0f6f4
# File: .github/workflows/workflow.yml

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  apply-azure-policy:    
    runs-on: ubuntu-latest
    steps:
    # Azure Login at management group scope requires allow-no-subscriptions to be set to true
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_3ab0f6f4}}
        allow-no-subscriptions: true

    - name: Checkout
      uses: actions/checkout@v2 

    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      with:      
        paths:  |                
          initiatives/test_193d8f9846a6494b976cc773/**
        
