name: manage-azure-policy-3ab0f6f4
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'initiatives/test_193d8f9846a6494b976cc773/**'
#      - .github/workflows/manage-azure-policy-3ab0f6f4.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_3ab0f6f4}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      with:
        paths: |
          initiatives/test_193d8f9846a6494b976cc773/**
